In [2]:
import tensorflow as tf

In [3]:
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix=tf.constant(([10,7],[7,10]))
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim


2

In [8]:
matrix=tf.constant([[10.,7.],[10.,8.],[6.,5.]],dtype=tf.float16)
matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [10.,  8.],
       [ 6.,  5.]], dtype=float16)>

In [9]:
matrix.ndim

2

In [10]:
tensor=tf.constant([[[1,2,2],[1,3,4]],[[2,5,6],[2,7,8]]])
tensor


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 2],
        [1, 3, 4]],

       [[2, 5, 6],
        [2, 7, 8]]], dtype=int32)>

In [11]:
tensor.ndim

3

In [12]:
changeable_var=tf.Variable([10,7])
fixed_var=tf.constant([10,7])
changeable_var,fixed_var

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
changeable_var[0]=7

TypeError: ignored

In [15]:
changeable_var[0].assign(7)
changeable_var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
fixed_var[0].assign(6)

AttributeError: ignored

In [17]:
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))

In [18]:
print(random_1)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)


In [19]:
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))

In [20]:
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [21]:
tf.random.shuffle(random_1)
tf.random.set_seed(42) # global level seed

In [22]:
ones_tensor = tf.ones(shape=[10, 7], dtype=tf.int32)
ones_tensor

<tf.Tensor: shape=(10, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int32)>

In [23]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [24]:
import numpy as np
A=np.arange(1,25,dtype=np.int32)
A_t=tf.constant(A,shape=(2,3,4))
print(type(A))
print(type(A_t))
print(A_t)


<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)


In [25]:
rank_4_tensor=tf.zeros([2,3,4,5],dtype=tf.int32)
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int32)>

In [26]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=int32, numpy=
array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int32)>

In [27]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [28]:
rank_4_tensor.shape[0]

2

In [31]:
tf.size(rank_4_tensor).numpy()

120

In [32]:
#indexing
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]]], dtype=int32)>

In [33]:
#each first element but not last dimension
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int32, numpy=array([[[[0, 0, 0, 0, 0]]]], dtype=int32)>

In [35]:
rank_4_tensor[:1,:1,:,:]

<tf.Tensor: shape=(1, 1, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int32)>

In [38]:
#reshape
rank_2=tf.constant([[10,7],
                    [3,4]])
rank_2.ndim,rank_2.shape

(2, TensorShape([2, 2]))

In [39]:
#last item of each row
rank_2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [40]:
#add extra dimension to rank2>rank3
rank_3=rank_2[...,tf.newaxis]
rank_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [42]:
#also
tf.expand_dims(rank_2,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [43]:
tf.expand_dims(rank_2,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [45]:
#manipulating tensor /operations element wise
tensor=tf.constant([[10,7],
                    [3,4]])
tensor+1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  8],
       [ 4,  5]], dtype=int32)>

In [46]:
tensor#unchanbged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [48]:
tf.multiply(tensor,2)#faster

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]], dtype=int32)>

In [49]:
tf.add(tensor,3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 10],
       [ 6,  7]], dtype=int32)>

In [51]:
#matrix mult
tf.matmul(tensor,tensor)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [53]:
t1=tf.constant([[1,2,5],[7,2,1],[3,3,3]])
t2=tf.constant([[3,5],[6,7],[1,8]])
t1,t2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [54]:
tf.matmul(t1,t2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [55]:
t1@t2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [56]:
tensor.shape

TensorShape([2, 2])

In [57]:
m1=tf.constant([[1,2],[3,4],[5,6]])
m2=tf.constant([[7,8],[9,10],[11,12]])
m1,m2

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [58]:
tf.reshape(m2,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [60]:
tf.matmul(m1,tf.reshape(m2,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [61]:
tf.matmul(tf.reshape(m1,shape=(2,3)),m2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [64]:
#transpose
tf.transpose(m1),tf.reshape(m1,shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [66]:
tf.transpose(m1)@m2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [68]:
#the dot
#tf.tensordot #requires transpose
tf.tensordot(tf.transpose(m1),m2,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
#change the datatypes

In [5]:
B=tf.constant([1.4,4.2])
C=tf.constant([2,2])
B,C


(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.4, 4.2], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>)

In [7]:
#reduced precision
B=tf.cast(B,dtype=tf.float16)

In [10]:
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.4, 4.2], dtype=float16)>

In [11]:
#aggregating
D=tf.constant([-7,-10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [29]:
import numpy as np
E=tf.constant(np.random.randint(0,100,size=50),dtype=tf.int32)
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([81, 54, 39,  3, 14, 72, 96, 51, 91, 80, 39, 21, 34, 43, 67, 79, 50,
       78, 37, 63, 86, 70,  8, 23, 86, 17, 37, 90, 82, 99, 56, 97, 91, 28,
       14, 67, 45, 34, 11, 54, 57, 40, 10, 52, 97, 36, 39, 82, 60,  8],
      dtype=int32)>

In [17]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [20]:
tf.reduce_min(E).numpy()

0

In [21]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [23]:
tf.reduce_mean(E).numpy()

50

In [24]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2518>

In [39]:
E=tf.cast(E,dtype=tf.float32)
var=tf.math.reduce_variance(E).numpy()
print(var)
print(tf.sqrt(var).numpy())


789.7503
28.102497


In [42]:
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [43]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [44]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [45]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [48]:
#squeezing
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [49]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [52]:
G_squeezed=tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

In [57]:
#one hot encoding
some_list=[0,1,2,3]
tf.one_hot(some_list,2)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [55]:
tf.one_hot(some_list,4,on_value="yoyo",off_value="fofo")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yoyo', b'fofo', b'fofo', b'fofo'],
       [b'fofo', b'yoyo', b'fofo', b'fofo'],
       [b'fofo', b'fofo', b'yoyo', b'fofo'],
       [b'fofo', b'fofo', b'fofo', b'yoyo']], dtype=object)>